apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kafka-cluster
spec:
  components:
    - name: "kafka-cluster"
      type: "k8s-objects"
      properties: 
        objects:
          - apiVersion: kafka.kubedoop.dev/v1alpha1
            kind: KafkaCluster
            metadata: 
              name: simple-kafka
            spec:
              image:
                productVersion: 3.7.1
              clusterConfig:
                authentication:
                  - authenticationClass: kafka-client-auth-tls
                tls:
                  internalSecretClass: kafka-internal-tls
                  serverSecretClass: tls
                zookeeperConfigMapName: simple-kafka-znode
              brokers:
                config:
                  bootstrapListenerClass: external-unstable
                  brokerListenerClass: external-unstable
                roleGroups:
                  default:
                    replicas: 3
          - apiVersion: authentication.kubedoop.dev/v1alpha1
            kind: AuthenticationClass
            metadata:
              name: kafka-client-auth-tls
            spec:
              provider:
                tls:
                  clientCertSecretClass: kafka-client-auth-secret
          - apiVersion: secrets.kubedoop.dev/v1alpha1
            kind: SecretClass
            metadata:
              name: kafka-client-auth-secret
            spec:
              backend:
                autoTls:
                  ca:
                    secret:
                      name: secret-provisioner-tls-kafka-client-ca
                      namespace: demo
                    autoGenerate: true
          - apiVersion: secrets.kubedoop.dev/v1alpha1
            kind: SecretClass
            metadata:
              name: kafka-internal-tls
            spec:
              backend:
                autoTls:
                  ca:
                    secret:
                      name: secret-provisioner-kafka-internal-tls-ca
                      namespace: demo
                    autoGenerate: true
  policies:
    - name: topology-demo
      type: topology
      properties:
        clusters: ['local']
        namespace: demo