apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hdfs-cluster
spec:
  components:
    - name: "hdfs-cluster"
      type: "k8s-objects"
      properties: 
        objects:
          - apiVersion: hdfs.kubedoop.dev/v1alpha1
            kind: HdfsCluster
            metadata: 
              name: simple-hdfs
            spec:
              image:
                productVersion: 3.4.0
              clusterConfig:
                zookeeperConfigMapName: simple-hdfs-znode
                dfsReplication: 1
              nameNodes:
                config:
                  listenerClass: external-stable
                roleGroups:
                  default:
                    replicas: 2
              dataNodes:
                config:
                  listenerClass: external-unstable
                roleGroups:
                  default:
                    replicas: 1
              journalNodes:
                roleGroups:
                  default:
                    replicas: 1
  policies:
    - name: topology-demo
      type: topology
      properties:
        clusters: ['local']
        namespace: demo