apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: zookeeper-cluster
spec:
  components:
    - name: "zookeeper-cluster"
      type: "k8s-objects"
      properties: 
        objects:
          - apiVersion: zookeeper.kubedoop.dev/v1alpha1
            kind: ZookeeperCluster
            metadata:
              name: simple-zk
            spec:
              image:
                productVersion: 3.9.2
              servers:
                roleGroups:
                  default:
                    replicas: 1
          - apiVersion: zookeeper.kubedoop.dev/v1alpha1
            kind: ZookeeperZnode
            metadata:
              name: simple-hdfs-znode
            spec:
              clusterRef:
                name: simple-zk
  policies:
    - name: topology-demo
      type: topology
      properties:
        clusters: ['local']
        namespace: demo