apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hive-cluster
spec:
  components:
    - name: "hive-cluster"
      type: "k8s-objects"
      properties: 
        objects:
          - apiVersion: hive.kubedoop.dev/v1alpha1
            kind: HiveCluster
            metadata: 
              name: simple-hive-derby
            spec:
              image:
                productVersion: 4.0.1
                kubedoopVersion: 0.0.0-dev
              clusterConfig:
                database:
                  connString: jdbc:derby:;databaseName=/tmp/hive;create=true
                  credentialsSecret: hive-credentials
                  dbType: derby
              metastore:
                roleGroups:
                  default:
                    replicas: 1
                    config:
                      resources:
                        cpu:
                          min: 300m
                          max: "2"
                        memory:
                          limit: 5Gi
          - apiVersion: v1
            kind: Secret
              metadata:
                name: hive-credentials
              type: Opaque
              stringData:
                username: APP
                password: mine
  policies:
    - name: topology-demo
      type: topology
      properties:
        clusters: ['local']
        namespace: demo